version: '3'
services:
  eventstore.db:
      image: eventstore/eventstore:23.10.0-bookworm-slim
      environment:
        - EVENTSTORE_CLUSTER_SIZE=1
        - EVENTSTORE_RUN_PROJECTIONS=All
        - EVENTSTORE_START_STANDARD_PROJECTIONS=true
        - EVENTSTORE_EXT_TCP_PORT=1113
        - EVENTSTORE_HTTP_PORT=2113
        - EVENTSTORE_INSECURE=true
        - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
        - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      ports:
        - "1113:1113"
        - "2113:2113"
      volumes:
        - type: volume
          source: eventstore-volume-data
          target: /var/lib/eventstore
        - type: volume
          source: eventstore-volume-logs
          target: /var/log/eventstore
  ledgerd:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - HTTP_ADDRESS=${HTTP_ADDRESS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "80:8000"
    depends_on:
      - eventstore.db
volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
