version: '3'
services:
  db.eventstore:
      image: eventstore/eventstore:23.10.0-bookworm-slim
      environment:
        - EVENTSTORE_CLUSTER_SIZE=1
        - EVENTSTORE_RUN_PROJECTIONS=All
        - EVENTSTORE_START_STANDARD_PROJECTIONS=true
        - EVENTSTORE_EXT_TCP_PORT=1113
        - EVENTSTORE_HTTP_PORT=2113
        - EVENTSTORE_INSECURE=true
        - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
        - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      ports:
        - "1113:1113"
        - "2113:2113"
      volumes:
        - type: volume
          source: eventstore-volume-data
          target: /var/lib/eventstore
        - type: volume
          source: eventstore-volume-logs
          target: /var/log/eventstore
      profiles: 
        - full
        - dev
  db.postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=${DB_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-volume-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    profiles: 
      - full
      - dev
  redis:
    image: redis:7.2.4-alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    ports:
      - "6379:6379"
    profiles: 
      - full
      - dev
  ledgerd:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - HTTP_ADDRESS=${HTTP_ADDRESS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "80:8000"
    depends_on:
      # eventstore.db
      redis:
        condition: service_healthy 
    profiles: 
      - full
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db.postgres
    profiles: 
      - dev
volumes:
  postgresql-volume-data:
  eventstore-volume-data:
  eventstore-volume-logs:
